version: '3.8'
services:
  workload:
    build: ./workload
    container_name: workload
    env_file:
      - .env
    environment:
      INFLUX_HOST: 141.45.165.136
      INFLUX_PORT: 8086
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      SCENARIO: ${SCENARIO}
      POINTS: ${POINTS}
      MEASUREMENTS: ${MEASUREMENTS}
      TAGS: ${TAGS}
      FLUSH_INTERVAL_MS: ${FLUSH_INTERVAL_MS}
      USE_GZIP: ${USE_GZIP}
      BATCH_SIZE: ${BATCH_SIZE}
      PARALLEL_CLIENTS: ${PARALLEL_CLIENTS}
      TIMESTAMP_SPAN_SEC: ${TIMESTAMP_SPAN_SEC}
      SERIES_MULTIPLIER: ${SERIES_MULTIPLIER}
      DURATION_SEC: ${DURATION_SEC}
      REPORT_NAME: ${REPORT_NAME}
      WORKLOAD_LOG_DIR: ${WORKLOAD_LOG_DIR:-/logs/workload}
      SCENARIO_MATRIX_PATH: /app/config/scenario_matrix.yaml
    volumes:
      - ./logs/workload:/logs/workload
      - ./workload/config/scenario_matrix.yaml:/app/config/scenario_matrix.yaml:ro
      - ./run:/run
    command: ["/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1'
        reservations:
          memory: 4G
          cpus: '0.5'
    networks:
      - public

volumes:
  influxdb-data:
    driver: local

networks:
  public:
    driver: bridge
